#marcin_admin_homepage:
#    path:     /
#    defaults: { _controller: MarcinAdminBundle:Default:index }
    
marcin_admin_dashboard:
    resource: "@MarcinAdminBundle/Controller/DashboardController.php"
    type: annotation
    prefix: /
    
marcin_admin_username:
    resource: "@MarcinAdminBundle/Controller/UsernameController.php"
    type: annotation
    prefix: /u/user
    
marcin_admin_shoper:
    resource: "@MarcinAdminBundle/Controller/ShoperController.php"
    type: annotation
    prefix: /u/shoper
    
marcin_admin_invest:
    resource: "@MarcinAdminBundle/Controller/InvestController.php"
    type: annotation
    prefix: /i/invest
    
marcin_admin_partnerplast:
    resource: "@MarcinAdminBundle/Controller/PartnerplastController.php"
    type: annotation
    prefix: /p/partner
    
marcin_admin_selena:
    resource: "@MarcinAdminBundle/Controller/SelenaController.php"
    type: annotation
    prefix: /s/selena
    
marcin_admin_hanno:
    resource: "@MarcinAdminBundle/Controller/HannoController.php"
    type: annotation
    prefix: /h/hanno
    
marcin_admin_awax:
    resource: "@MarcinAdminBundle/Controller/AwaxController.php"
    type: annotation
    prefix: /a/awax
    
marcin_admin_zygmar:
    resource: "@MarcinAdminBundle/Controller/ZygmarController.php"
    type: annotation
    prefix: /z/zygmar
    
marcin_admin_allzam:
    resource: "@MarcinAdminBundle/Controller/AllzamowieniaController.php"
    type: annotation
    prefix: /all/zamowienia
    

#marcin_admin_username_form:
#    resource: "@MarcinAdminBundle/Controller/UsernameController.php"
#    prefix: /u/user/form/{id}
    
#marcin_admin_dashboard_update:
#    pattern:  /form/update-complete/{id}
#    defaults: { _controller: MarcinAdminBundle:Dashboard:updateZam, _format:json}
#    requirements:
#        _method:  POST|GET|PUT
#    options:
#        expose: true